name: Makefile CI

on:
  push:
    branches: [ "master", "dermatest" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Run tests
      run: make test

    - name: Build artefact
      run: make build
